# https://docs.github.com/en/actions

name: "Integrate"

on:
  pull_request: null
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build"

    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        language:
          - "ja"
        php:
          - "8.4"

    steps:
      - name: "Checkout php/doc-${{ matrix.language }}"
        uses: "actions/checkout@v4"
        with:
          path: "${{ matrix.language }}"
          repository: "php/doc-${{ matrix.language }}"

      - name: "Checkout php/doc-en as fallback"
        if: "matrix.language != 'en'"
        uses: "actions/checkout@v4"
        with:
          path: "en"
          repository: "php/doc-en"

      - name: "Checkout php/doc-base"
        uses: "actions/checkout@v4"
        with:
          path: "doc-base"
          repository: "php/doc-base"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - run: php -v
      - run: php -m
      - run: php -i

      - name: "Build documentation for ${{ matrix.language }}"
        run: "php doc-base/configure.php --disable-libxml-check --enable-xml-details --redirect-stderr-to-stdout --with-lang=${{ matrix.language }}"
